### ISSUE TITLE
Missing configuration files

### ISSUE THREAD

**Issue by sukesh-ak** [stuartleaver/flight-tracker-cosmosdb-functions-serverless#2] opened 2020-07-12 21:36 UTC
Was trying to run this to understand how it works.
Some settings files are missing. Can you please look into it?

**Comment by stuartleaver** [comment] 2020-07-13 17:02
@sukesh-ak Would it be possible to let me know what setting files are missing, please?

If you are running the code locally in VS Code, the `.vscode` folder will need to be there with settings files. Are these the ones you mean? If so, these are not normally committed to source control as they should be created automatically. If you need any help with this, let me know.

Again, if running locally, you will need to set up `local.settings.json` for the Function App code and `appsettings.Development.json` for the Web App code. Again, are these the ones you mean? If so, they are not here as they include secrets, but they should look like the following:

functions:

```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "<add value>",
    "CosmosDbConnectionString": "<add value>",
    "AzureSignalRConnectionString": "<add value>",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet"
  },
  "Host": {
    "CORS": "*"
  }
}
```

web:
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "cors": {
    "rules": [
      {
        "origin": "*",
        "allow": true
      }
    ]},
  "KeyVaultName": "flighttracker",
  "FunctionsBaseUrl": "https://localhost:7071",
  "ImageSpriteColour": "blue"
}
```

Do let me know if that helps.

**Comment by sukesh-ak** [comment] 2020-07-14 06:55
Thanks @stuartleaver for your response.
I was using Visual Studio and not VS Code, so those files were missing.
I finally got till the map working now. Need to change the html map page to cater to my scenario now.

My project flow is like below
> Device > Iot Hub > Event Grid > Azure Functions > CosmosDB > CosmosDB Feed > Azure Functions > Azure SignalR > Azure Static Website

**Comment by stuartleaver** [comment] 2020-07-17 17:25
Looks like this is now resolved so closing. If the problem is still there, just let me know.

**Closed as completed by stuartleaver** 2020-07-17 17:25 UTC
Labels: question
